### PR TITLE
DOCS-6268: MongoDB Atlas integration docs updates

### PR DESCRIPTION
**Pull request by drichards-87**
### What does this PR do?

Updates the MongoDB Atlas integration docs. See DOCS-6268 for details.

### Motivation

What inspired you to submit this pull request?

DOCS-6268

### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [X] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by drichards-87** [comment]
@romandatadog Here's the PR for the updates to the MongoDB Atlas docs. Side note, could you (or someone who would know) help double-check the image I included in the PR? For some reason, I'm not able to get it to display when running the Docs build locally even though I'm pretty sure I'm following the image guidelines correctly. Thanks!

**Review by romandatadog — APPROVED** [review]

**Comment by romandatadog** [comment]
The aspect ratio for the image at `images/mongodb_atlas_dashboard.png` is 1.8, but should be 16:9 (1.78).

**Review by romandatadog — CHANGES_REQUESTED** [review]
The aspect ratio for the image at `images/mongodb_atlas_dashboard.png` is 1.8, but should be 16:9 (1.78).

**Comment by drichards-87** [comment]
> The aspect ratio for the image at `images/mongodb_atlas_dashboard.png` is 1.8, but should be 16:9 (1.78).

Got it. I took it from the blog post, so I'll see if I can resize it without losing any image quality. If not, I'll see if I can reproduce the image myself.

**Review by romandatadog — APPROVED** [review]

**Comment by drichards-87** [comment]
@romandatadog Just FYI, it looks like I don't have the proper permissions to merge this PR. So you may have to do it for me. Side note, I updated the image to 1440x810 to get the 16:9 aspect ratio, so it should work now 🤞.

**Review by romandatadog — APPROVED** [review]

**Review by ZacharyAnderson — APPROVED** [review]

**Pull request merged**
