### PR TITLE
PureFB Version 1.0.4 - add new metric purefb.nfs.export_rule

### PR DESCRIPTION
**Pull request by chrroberts-pure**
### What does this PR do?

New metrics are now supported by our exporter. This PR is to add these metrics to our Datadog Check for PureFB.

### Motivation

To get the latest and greatest to our mutual customers. 

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### CODE REVIEW

**Comment by chrroberts-pure** [comment]
I'm a little confused with the models check, I see they were updated in #2088 a few days ago- I updated with ddev 6.0 and they seemed to agree with #2088, but the check is using ddev 3.10. Please confirm.

**Comment by emarsha94** [comment]
Hey @chrroberts-pure It looks like all validations are successful so I think we are good here. To confirm, you are only adding support for another metric but everything else is backwards compatible (no breaking change has been made)?

**Comment by chrroberts-pure** [comment]
That is correct @emarsha94 . Only the new metric and related documentation has been changed.

**Review by emarsha94 — APPROVED** [review]
Thank you for clarifying! Approving from my end

**Review by JoshPatel13 — APPROVED** [review]

**Review by alopezz — APPROVED** [review]

**Pull request merged**
