### PR TITLE
(DOCS-5505) Replace broken developer tool links in READMEs

### PR DESCRIPTION
**Pull request by hestonhoffman**
### What does this PR do?

Fixes some links to the developer tools documentation, which is now on a different page.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by hestonhoffman** [comment]
Ran the commands to sync the config files and comitted the changes, but it's still failing 🤷

**Review by estherk15 — APPROVED** [review]

**Comment by hestonhoffman** [comment]
Thanks @yzhan289, I actually wasn't trying to make any updates to the conf files. The changes here are a result of running the validate command with the `-e` flag to get rid of the validation error. I'll back those changes out.

**Comment by hestonhoffman** [comment]
@yzhan289 Can I get a re-review? Only adjusting some README files.

**Comment by yzhan289** [comment]
> Thanks @yzhan289, I actually wasn't trying to make any updates to the conf files. The changes here are a result of running the validate command with the `-e` flag to get rid of the validation error. I'll back those changes out.

What is the `-e` flag? Are you saying that when you run `ddev validate config __ -s` it generated the bad config?

**Comment by hestonhoffman** [comment]
> > Thanks @yzhan289, I actually wasn't trying to make any updates to the conf files. The changes here are a result of running the validate command with the `-e` flag to get rid of the validation error. I'll back those changes out.
> 
> What is the `-e` flag? Are you saying that when you run `ddev validate config __ -s` it generated the bad config?

I ran `ddev validate config hikaricp -s` first (and again for fluentbit) . Nothing happened. I then ran `ddev -e validate config hikaricp -s` (the `-e` option for `integrations-extras` has been recommended to me in the past). This time, it made those changes to the conf files.

**Comment by yzhan289** [comment]
> I ran `ddev validate config hikaricp -s` first (and again for fluentbit). Nothing happened. I then ran `ddev -e validate config hikaricp -s` (the `-e` option for `integrations-extras` has been recommended to me in the past). This time, it made those changes to the conf files.

Interesting, when I ran `ddev -e validate config hikaricp -s`, it just adds `ignore_connection_errors` as a new config but doesn't change the other values. Do you have the latest version of `ddev`? That may be why CI thinks your local `conf.yaml.example`s are bad. I can also push my updated `conf.yaml.example` to your branch, since otherwise this PR looks good.

**Comment by hestonhoffman** [comment]
> 

Yeah, I just reinstalled it before I made the PR, so I'm not sure what's going on there. If you want to push your updated version, that would be great 👍

**Comment by yzhan289** [comment]
Oops looks like the config models also needs to be synced. I'll push a commit to do so now.

**Review by yzhan289 — APPROVED** [review]

**Pull request merged**
