### PR TITLE
Additional facet additions

### PR DESCRIPTION
**Pull request by gregcoward**
### What does this PR do?

Update to all.json (saved view), adding additional facets

### Motivation

To improve dashboard visibility functionality

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by gregcoward** [comment]
Hello, I hope a pull request to the master is  the correct route.  The update includes a  slight update to 1 file, (all.json). - saved view.  I am adding in additional facets.

**Comment by gregcoward** [comment]
Our logs are delivered in JSON format, easily searchable and don’t need a log pipeline.  However, I do need  facets to be able to visualize certain fields, it’s my understanding from [here](https://docs.datadoghq.com/logs/explorer/facets/), (and in practice).  I am using the saved view to generate the necessary facets in the end-user’s environment.  The dashboard included in the integration works great except for missing one facet, (@rsp_code_class).   The pull request includes just a single file, (all.json – saved view).  I hope that makes sense 😊

**Review by emarsha94 — CHANGES_REQUESTED** [review]
Spoke via email - you will need to create and package a log pipeline in order to include out-of-the-box facets. Once done, we can add new images to the dashboard or update the overview if you would like to mention facets.

**Comment by gregcoward** [comment]
Hello, since our logs do not currently include a source field, I will not be able to integrate a pipeline.  As an alternative, (until our logs are updated) I will add in instructions for the end-user to create the four (4) required facets manually from the log search.  I'll close the pull request and open a new one with updated instructions.

**Pull request closed without merging**
