### PR TITLE
N2ws

### PR DESCRIPTION
**Pull request by eliadeini**
### What does this PR do?

Updates N2WS tile with new N2WS features for N2WS Backup & Recovery

### Motivation

What inspired you to submit this pull request?
N2WS Backup & Recovery version 4.0 is about to come out to the market, supporting also Azure cloud.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?
Added some Azure metrics in new dashboards

### CODE REVIEW

**Review by coignetp — CHANGES_REQUESTED** [review]
Hi @eliadeini, thanks for opening a new PR about this. Can you rebase to master and resolve conflicts?

**Comment by hithwen** [comment]
Hi, it seems this PR has conflicts that need to be fixed before it can be merged

**Comment by eliadeini** [comment]
> Hi, it seems this PR has conflicts that need to be fixed before it can be merged

Hi Julia, 
I don't have permissions to fix conflicts on your GitHub repository:
image

Basically, I want to override the old files with the new ones.

**Comment by hithwen** [comment]
Hi @eliadeini you don't need to fix the conflicts in Datadog's repo but on your fork. The PR cannot physically be merged (the button is disabled) if there are conflicts.

**Comment by eliadeini** [comment]
> Hi @eliadeini you don't need to fix the conflicts in Datadog's repo but on your fork. The PR cannot physically be merged (the button is disabled) if there are conflicts.

Hi, I created a new branch, and open a merge request at https://github.com/DataDog/integrations-extras/pull/860
Please review.

Thanks in advance, 
Eliad

**Comment by eliadeini** [comment]
Created a new branch and opened a new merge request: https://github.com/DataDog/integrations-extras/pull/860

**Pull request closed without merging**
