### PR TITLE
apollo: Update metric names and tags

### PR DESCRIPTION
**Pull request by glasser**
### What does this PR do?

Changes the metric and tag names used by our integration.

### Motivation

Earlier this year as part of a rebranding we upgraded this integration to be
called "Apollo" rather than "Apollo Engine". We are now changing the metrics to
start with `apollo.operations` rather than `apollo.engine.operations` and
changing the tag name from `service` to `graph`.

Note that our infrastructure will continue using the old metric names and tags
for existing integrations until users choose to migrate over to the new
one, so `metric_to_check` uses a list instead of naming just one metric.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Is it our job to notify the docs team? We definitely want to make sure this gets both to the docs and to the in-app integration tile. Note that the last change we made never made it to the in-app integration tile. (I'm also discussing this with support in ZD ticket 395468.)

### CODE REVIEW

**Comment by glasser** [comment]
(updated to have a list for `metric_to_check`)

**Comment by sachindshinde** [comment]
PR looks fine to me, although I'll defer to @dsahni and @scseanchow about docs steps and any subtleties here.

**Comment by ChristineTChen** [comment]
Hi @glasser, thanks for the PR! This look good to me, I'll merge once @DataDog/documentation team has taken a look ✅

**Review by apigirl — APPROVED** [review]
👍 from docs

**Comment by glasser** [comment]
Thanks @ChristineTChen and @apigirl !

I see the changes have already made it to https://docs.datadoghq.com/integrations/apollo/
That's great!

Do you need to take explicit steps to make these changes show up in the in-app integration tile (https://app.datadoghq.com/account/settings#integrations/apollo)? Note that changes from much earlier in the year such as #551 do not seem to have made it to the tile, at least in our account. (Unless the semantics are that integration documentation doesn't update for existing installations but does for new ones or something?)

**Comment by glasser** [comment]
I confirmed with a friend whose Datadog account has never used our integration that they are also seeing the many months out of date text in their in-app tile, fwiw.

**Comment by apigirl** [comment]
@glasser - we sync the tiles with updates from the readmes once a week, usually on Monday. So look for these changes to update into the app early next week!

**Comment by glasser** [comment]
@apigirl I see that the text in the overview and configuration tabs have updated in the app. Thanks!

This seems to not be updated yet:
- The metrics listed on the Metrics tab (doesn't have the new `apollo.operations.*` metrics)
- The name of the integration ("Apollo Engine" -> "Apollo") as visible on the top-level integrations list
- The integration logo

Is that a separate process?
Also I'm not sure how to tell if the change to the "prefix" has made it to the point of your system that all `apollo.*` metrics count as non-custom for billing purposes. I'll definitely need confirmation of that before I can make the change for our users.

**Comment by glasser** [comment]
(In the interest of not having too many threads, maybe follow up this on #729 ?)

**Pull request merged**
