### PR TITLE
Handle the use case where no databases have been created

### PR DESCRIPTION
**Pull request by maguec**
### What does this PR do?

When attempting to fetch the database usage statistics for a new cluster with 0 database created the Redis Enterprise API 404's due to the fact that there is no data yet to send.

It also updates the documents and blurs out some information on the screenshots in docs

### Motivation

One of our clients is seeing this

### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [X] Git history is clean
- [X] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

This can only be testing in a live environment.

### CODE REVIEW

**Review by ruthnaebeck — APPROVED** [review]
👍  for docs

**Review by sarah-witt — CHANGES_REQUESTED** [review]
Looks great! I have one small comment

**Comment by maguec** [comment]
@sarah-witt  codeowners updated - thanks!

**Review by sarah-witt — COMMENTED** [review]
Hi @maguec, I have one more small comment- do you mind updating the changelog? https://github.com/DataDog/integrations-extras/blob/master/redisenterprise/CHANGELOG.md

**Comment by maguec** [comment]
@sarah-witt Changelog updated as well

**Review by sarah-witt — APPROVED** [review]

**Pull request merged**
