### PR TITLE
Update Vercel dashboard

### PR DESCRIPTION
**Pull request by sfirrin**
### What does this PR do?

Update the Vercel dashboard
image

### Motivation

Making the Vercel dash more useful

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by ofek — CHANGES_REQUESTED** [review]
Can you please make 2 commits: one that formats this file and the other that actually does the update?

**Review by apigirl — COMMENTED** [review]
no docs review needed

**Review by ofek — APPROVED** [review]
https://github.com/DataDog/integrations-extras/pull/1716/commits/3da451d87fc6b6d34c80b9d5c6387be885ce4e56 looks good to me!

**Comment by FlorentClarret** [comment]
I synced the dashboard to staging if you want to take a look!

**Comment by sfirrin** [comment]
Thanks @ofek @FlorentClarret 

Any idea how to get the CI to run again?

**Pull request merged**
