### PR TITLE
[Portworx] Initial integration checkin

### PR DESCRIPTION
**Pull request by pault84**
Signed-off-by: Paul Theunis <paul@portworx.com>

### What does this PR do?

Adds an integration for Portworx metrics into datadog.

### Motivation

Feature has been requested by alot of our customers.

### Versioning

- [x] Bumped the version check in `manifest.json`
- [x] Updated `CHANGELOG.md`
- [ ] If PR impacts documentation, docs team has been notified or [an issue has been opened on the documentation repository](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Have not been able to get the automated test to work.
Could only get it to work with prometheus if I ran our product on the same node as the rake command.
The problem here is that we have a lot of pre-requisites to run our product (Kvdb, a bunch of mounted paths).
In the current file i tried hosting an http server that served metrics, but i have not been able to figure out how to present them to python in a way that is parseable.

### CODE REVIEW

**Comment by jeremy-lq** [comment]
Thanks for the PR, @pault84! integrations-extras is a community-driven repository for integrations written and maintained outside Datadog. While support is on a best-effort basis, we're happy to help with code reviews and testing. The integrations won't be bundled with the agent, but will be installable on an individual basis.

With that in mind, would you (and/or @portworx) be interested in being the initial maintainer for this integration? You'd be responsible for general code maintenance along with keeping an eye on PRs and issues. There's no specific time or duration commitment, but we do ask you only agree to become the maintainer if you feel it's something you'll be able to do for the foreseeable future. If you have any questions, let us know.

**Comment by pault84** [comment]
@jeremy-lq yes we would be responsible for maintaining this feature. 
We're currently talking with the folks at DataDog on having this integration being picked up on the product dashboard.

**Comment by jeremy-lq** [comment]
Thanks again, @pault84.

**Comment by dsahni** [comment]
Hi @pault84,

Can you please update the PR with the correct logo sizes?

Here are the specific sizes along with the filenames:
* 200x128px: saas_logos-bot.png
* 128x128px: avatars-bot.png
* 120x60px: saas_logos-small.png

**Comment by pault84** [comment]
Sure i thought i did but i'll work on that or get someone to get them for me.

**Comment by pault84** [comment]
I've uploaded the images. still no idea how to get this test to work. we'll need a working portworx instance to test properly.

**Comment by dsahni** [comment]
Closing this PR as this integration was added as part of https://github.com/DataDog/integrations-extras/pull/175

**Pull request closed without merging**
