### PR TITLE
Update/fix k6 dashboard with the screen endpoint's output

### PR DESCRIPTION
**Pull request by mostafa**
### What does this PR do?

This PR is going to fix the issue @hithwen mentioned in the https://github.com/DataDog/integrations-extras/pull/653 PR. I am now using the screen endpoint to update the dashboard.

### Motivation

@hithwen's comments about using unsupported new dashboard that I used in the previous PR: https://github.com/DataDog/integrations-extras/pull/653 

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

@ppcano: Please review.

### CODE REVIEW

**Comment by hithwen** [comment]
It seems this time everything is ok

**Comment by mostafa** [comment]
I used `ddev` to validate everything locally before sending the PR.

**Comment by hithwen** [comment]
Yes, but ddev was doing the wrong validation before ;)

**Comment by mostafa** [comment]
Well, I didn't notice, aince I haven't used it before. 😄

**Comment by mostafa** [comment]
@hithwen Looks like the dashboard does not work. No widget is shown.

**Pull request merged**
