### PR TITLE
Update Mendix integration logo

### PR DESCRIPTION
**Pull request by pappachino**
### What does this PR do?

Update the Mendix logo for dark and light themes.

### CODE REVIEW

**Review by bgoldberg122 — APPROVED** [review]

**Review by anawishnoff — APPROVED** [review]

**Comment by anawishnoff** [comment]
Thanks for opening this PR! Once these logos are synced on our end we can merge this PR.

**Review by mukulchugh — COMMENTED** [review]
looks go to me

**Review by FlorentClarret — APPROVED** [review]

**Comment by pappachino** [comment]
@anawishnoff @FlorentClarret If all is good, can we merge this please? Thanks!!

**Comment by anawishnoff** [comment]
@pappachino As soon as we can create the logos on our end, we'll be able to merge this. We'll keep you posted, thanks!

**Comment by pappachino** [comment]
@anawishnoff  Any updates?

**Comment by anawishnoff** [comment]
This is good to go now! @bgoldberg122

**Pull request merged**
