### PR TITLE
[nsq] adding integration

### PR DESCRIPTION
**Pull request by truthbk**
# What's this PR do?

Adds an NSQ integration

Orginally written by @gphat aka @cory-stripe (https://github.com/DataDog/dd-agent/pull/2281)

# Information About The Integration

Adds the following metrics by polling NSQ's `/stats` endpoint:
- `nsq.topic_count`
- `nsq.topic.channel_count`
- `nsq.topic` (all tagged with `topic_name`):
  - `depth`
  - `backend_depth`
  - `message_count` (count, not gauge)
- `nsq.topic.channel` (all tagged with `topic_name` and `channel_name`):
  - `depth`
  - `backend_depth`
  - `in_flight_count`
  - `deferred_count`
  - `message_count` (count, not gauge)
  - `requeue_count`
  - `timeout_count`
  - `e2e_processing_latency.p50` (nanoseconds)
  - `e2e_processing_latency.p95` (nanoseconds)
  - `e2e_processing_latency.p99` (nanoseconds)
  - `e2e_processing_latency.p999` (nanoseconds)
  - `e2e_processing_latency.p9999` (nanoseconds)
- `nsq.topic.channel.client` (all tagged with `topic_name`, `channel_name` and `client_id`, `client_version`, `tls`, `user_agent`, `deflate` and `snappy`):
  - `ready_count`
  - `in_flight_count`
  - `message_count` (count, not gauge)
  - `finish_count`
  - `requeue_count`
# Notes
- Should this be `nsq` or `nsqd`? 
- We'll need to do a pass with @danielhfrank and verify we got everything
- This is working locally on a single test machine atm.
- More information to come, notably a summary of metrics.

r? @rhwlo @danielhfrank @smarden1
cc @remh

### CODE REVIEW

**Comment by jeremy-lq** [comment]
@cory-stripe (@gphat) has agreed to be the maintainer for this check.

**Comment by cory-stripe** [comment]
Indeed!

**Comment by gmmeyer** [comment]
@cory-stripe I think this is great! I fixed the test fixture loading, but the test is still failing. Do you know what's wrong with it? After it's fixed I don't see much else that would prevent us from merging it!

**Comment by jeremy-lq** [comment]
Chatted with Cory, and re-opening at his request.

**Pull request closed without merging**
