### PR TITLE
[f5check] Adding integration.

### PR DESCRIPTION
**Pull request by truthbk**
### What does this PR do?

Originally written by @KCarretto at https://github.com/DataDog/dd-agent/pull/2743

The goal of this pull request was to poll a F5 BIGIP device for metrics and to send
that information to DataDog. We decided to make an AgentCheck to collect and 
report these metrics and attempted to make the check as adaptive as possible. 
This was achieved by using SNMP and the F5 specific MIB files to query the 
device for metric information stored in data structures in the class definition.
### Motivation

We wanted to put metrics regarding the F5 BIGIP load-balancer into DataDog.
### Additional Notes

**System Dependencies:**
easysnmp : To be installed by the embedded pip.
net-snmp : Requires version 5.7 or later
F5 BIGIP MIB files : Can be downloaded from the load-balancer.

We have created an issue for this request, which can be found [here](https://github.com/DataDog/dd-agent/issues/2742).

### CODE REVIEW

**Comment by truthbk** [comment]
Related omnibus PR: https://github.com/DataDog/omnibus-software/pull/69

**Comment by irabinovitch** [comment]
@KCarretto Let us know if you need a hand with getting tests passing, etc.  Feel free to stop by our [office hours](https://github.com/DataDog/dd-agent/wiki/Community-Office-Hours) as well if we can help.  Next one is this morning at 10:30 PT / 13:30 EST.

**Comment by benjamincrom** [comment]
Reopening in support of customer

**Comment by greg-savage** [comment]
Is there any progress on this?  This would help my company out a lot.

**Comment by okunc** [comment]
Can you please reopen this one again? We'd find it very useful!

**Comment by therve** [comment]
We have support for SNMP in the core repository, and now an official F5 profile: https://github.com/DataDog/integrations-core/blob/master/snmp/datadog_checks/snmp/data/profiles/f5-big-ip.yaml. Can you try this out? Thanks.

**Comment by hithwen** [comment]
As a note: You will need to manually update the snmp integration to `1.12.0` with the [integration command](https://docs.datadoghq.com/agent/guide/integration-management/#install) or wait for the agent `6.15` release that will come out in the next few weeks. We would really appreciate feedback.

**Pull request closed without merging**
