### PR TITLE
Corrected data source tag.

### PR DESCRIPTION
**Pull request by srinivas-bitla**
### What does this PR do?

Corrected data source tag from service to source.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by srinivas-bitla** [comment]
Can someone please help answer why this "validate-assets" check is failing? It says "An internal error occured" but provides no other details.

**Comment by nmuesch** [comment]
Apologies, there was an intermittent error on our end, but I retried it on my side and it looks like everything's green again.

**Comment by anawishnoff** [comment]
Hey @srinivas-bitla , can you please update your branch with the latest changes from master?

**Comment by srinivas-bitla** [comment]
@anawishnoff Done.

**Comment by anawishnoff** [comment]
@nmuesch is this good to merge?

**Review by nmuesch — APPROVED** [review]

**Pull request merged**
