### PR TITLE
update the link of Federator.ai feature demo video.

### PR DESCRIPTION
**Pull request by chenyingtz**
### What does this PR do?

update the link of Federator.ai feature demo video.

### Motivation

update the link of Federator.ai feature demo video.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by sarah-witt — APPROVED** [review]
Looks good for agent integrations!

**Review by kayayarai — APPROVED** [review]

**Comment by chenyingtz** [comment]
hi,
we check our Federator.ai Integration on Datadog dashbord, our [ProphetStor Federator.ai Feature Demo] link is still the old link. Do we miss any part? or any file we haven't update it right?
https://app.datadoghq.com/account/settings#integrations/federatorai

**Comment by kayayarai** [comment]
@chenyingtz You've done everything right. Sometimes it takes a few days for the docs and the in-app tile to sync. @sarah-witt are you able to nudge the sync?

**Comment by chenyingtz** [comment]
hi,
we can see our [ProphetStor Federator.ai Feature Demo] link is the latest link now, thanks!

**Pull request merged**
