### PR TITLE
Added Bind9 dns integration to collect dns server metrics.

### PR DESCRIPTION
**Pull request by ashuvyas45**
### What does this PR do?

A brief description of the change being made with this pull request.

An integration for Bind9 DNS server which collect data from bind9 statistics channel and sends the metrics such as queryTypes, Opcodes, nsstats, Zonestats, responseTime, configTime, resstat and sockstats to datadog.

### Motivation

What inspired you to submit this pull request?

Many people use bind9 to run private DNS and there is currently no agent check present for the same.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [ ] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by jeremy-lq** [comment]
Thanks for the PR, @ashuvyas45! integrations-extras is a community-driven repository for integrations written and maintained outside Datadog. While support is on a best-effort basis, we're happy to help with code reviews and testing. The integrations won't be bundled with the agent, but will be installable on an individual basis.

With that in mind, would you be interested in being the initial maintainer for this integration? You'd be responsible for general code maintenance along with keeping an eye on PRs and issues. There's no specific time or duration commitment, but we do ask you only agree to become the maintainer if you feel it's something you'll be able to do for the foreseeable future. If you have any questions, let us know.

**Comment by ashuvyas45** [comment]
@jeremy-lq Thank you accepting the PR and to let us contribute on the project. We will be grateful to be the maintainer of this integration and would work on any issue if arise in the future.

**Comment by ofek** [comment]
@ashuvyas45 Hello again! Have you had a chance to look at this?

**Comment by davalpargal** [comment]
@ofek I changed the directory name to bind9 and indentation to 4 spaces.
Regarding the failing test , are we required to test if the network call to BIND9 stats port works or not. If not , we can remove the failing test.

Also , Can you please explain me an @ashuvyas45  about why exactly the travis-ci is failing.
Thanks in advance

**Comment by ofek** [comment]
@davalpargal Thank you! I added the missing dependency. Could you or @ashuvyas45 fix the tests?

**Comment by ofek** [comment]
@davalpargal @ashuvyas45 Hello again! Do either of you have a few minutes to spare to fix the tests? Then we can get this merged 🙂

**Comment by ofek** [comment]
@davalpargal @ashuvyas45 Hello again! Any progress on this?

**Comment by ofek** [comment]
@davalpargal @ashuvyas45 Hello again! Need any help on this?

**Comment by ashuvyas45** [comment]
@ofek  I have fixed the issue with the mocking. Test are running fine now. Can you please check

**Comment by ashuvyas45** [comment]
@ofek Thank you for the fix. I see some test are failing but they are passing in my local. Also the error about the description and metric prefix, but metric prefix are optional in manifest file as per the documents

**Comment by ofek** [comment]
@ashuvyas45 My pleasure! My goal is to get ci passing and merge this by tomorrow afternoon

**Comment by ofek** [comment]
@ashuvyas45 Everything is passing now except the datetime parser. Is the code wrong or is the test assertion wrong?

**Comment by ashuvyas45** [comment]
@ofek  I will look into and see what is the problem

**Comment by ashuvyas45** [comment]
@ofek  You are great support in this thank you

**Pull request merged**
