### PR TITLE
[LOI-156] Add tailscale integration for logs

### PR DESCRIPTION
**Pull request by txominpelu**
### What does this PR do?

[[LOI-156](https://datadoghq.atlassian.net/browse/LOI-156)] Add tailscale integrations to be able to install the integration when new logs are added.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

[LOI-156]: https://datadoghq.atlassian.net/browse/LOI-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nmuesch — APPROVED** [review]

**Comment by txominpelu** [comment]
is it safe to merge this one @nmuesch ?

**Comment by nmuesch** [comment]
@txominpelu I'm working on verifying a couple final pieces, but hoping to merge within the next 20 minutes

**Review by jhgilbert — APPROVED** [review]

**Comment by nmuesch** [comment]
Confirmed on staging that things look good. Merging

**Comment by txominpelu** [comment]
Thanks a lot @nmuesch ! 🙇

**Pull request merged**
