### PR TITLE
Ensure all integrations that emmit metrics define a metric_to_check

### PR DESCRIPTION
**Pull request by hithwen**
To allow enabling a new validation that will enforce it

### CODE REVIEW

**Comment by hithwen** [comment]
Pinging @tsein-bc @DavidFlamini @monganai @abtreece @dbyron0 @KosukeKamiya

**Review by KealanMaas — APPROVED** [review]
Flume change LGTM 👍

**Review by monganai — APPROVED** [review]
LGTM for Pihole 👍

**Comment by KosukeKamiya** [comment]
LGTM for Zabbix. 👍 
Thank you!

**Comment by dbyron0** [comment]
unbound LGTM

**Comment by abtreece** [comment]
Should be fine for riak_repl. 👍

**Pull request merged**
