### PR TITLE
N2WS-18718: Alerts filtering fix on dashboards

### PR DESCRIPTION
**Pull request by eliadeini**
### What does this PR do?

A bug fix for alerts list on N2WS dashboards

### Motivation

A bug fix

### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [X] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?
Filtering alerts by user and host on N2WS dashboards didn't work well since the user filter was not defined correctly.

### CODE REVIEW

**Comment by hithwen** [comment]
Hallo @eliadeini, the PR has conflicts. Can you fix them?

**Comment by eliadeini** [comment]
> Hallo @eliadeini, the PR has conflicts. Can you fix them?

Done.
Thanks

**Comment by hithwen** [comment]
Hi @eliadeini  we had an issue with master so the builds were broken, would you mind rebasing again?

**Comment by eliadeini** [comment]
> Hi @eliadeini we had an issue with master so the builds were broken, would you mind rebasing again?

Hi, I tried, but I see that tests are failing. Can you advise?

**Comment by hithwen** [comment]
> Hi, I tried, but I see that tests are failing. Can you advise?
When you rebased master was broken, you need to do it again. Sorry for the inconvenience.

**Comment by eliadeini** [comment]
> > Hi, I tried, but I see that tests are failing. Can you advise?
> 
> When you rebased master was broken, you need to do it again. Sorry for the inconvenience.

Sorry, after fighting the rebase, I decided to open a clean branch with a new PR: https://github.com/DataDog/integrations-extras/pull/899

Thanks,
Eliad

**Pull request closed without merging**
