### PR TITLE
Update k6 dashboard and the metadata of the metrics

### PR DESCRIPTION
**Pull request by mostafa**
### What does this PR do?

In this PR, I've added `unit_name` and `per_unit_name` to some metrics' metadata, namely `k6.http_reqs`, `k6.vus` and `k6.vus_max`. I've also updated the dashboard to include `test_run_id` as template variable, which is then included in all charts. `q`s for each chart has also been corrected.

### Motivation

Previously, only k6 OSS could send metrics to DataDog, but we have also added a feature to export metrics from our cloud service, k6 Cloud. So, we want to have a single dashboard for both k6 OSS and k6 Cloud. The changes in this PR fulfills this objective.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### CODE REVIEW

**Comment by hithwen** [comment]
Ping @ppcano for review

**Comment by mostafa** [comment]
Hey @hithwen,

I work for the same company, and we (@ppcano and I) work in the same team.

**Comment by hithwen** [comment]
Then it should be easy to get him to approve the pr ;)

**Comment by mostafa** [comment]
He's on vacation. :)

**Comment by hithwen** [comment]
Hallo @mostafa @ppcano sorry about this, it seems it was not covered by the automatic validation but this dashboard is using the format from the `dash` endpoint which is not supported for default dashboards (and as a result this dashboards renders blank). Default dashboards need to have the `/screen` or `/time` endpoints formatting.

**Comment by mostafa** [comment]
Hey @hithwen,
Can you point me to some docs about this?

**Comment by hithwen** [comment]
Hi @mostafa here you have some docs https://datadoghq.dev/integrations-core/guidelines/dashboards/

**Pull request merged**
