### PR TITLE
[file] new check to test for a file's existence

### PR DESCRIPTION
**Pull request by truthbk**
### What does this PR do?

Adds a check for file existence

This PR was originally written by @antifuchs (https://github.com/DataDog/dd-agent/pull/2411)

The file.py check allows the agent to test for whether files exist in the local file system, and if they do, emit a metric for how long they have existed. This is particularly useful for files like Debian's "package upgrades require a reboot" marker in /var/run/, or local puppet facts meant to be kept around only for a short time.

I have added almost no documentation to this check (mostly out of ignorance what format / locations are desired!), but would be interested in learning how you all prefer the check docs to be written.

### Testing

I added an integration test for the metric and service_check behavior. We're also running this check on our infra to test for exactly the presence of /var/run/reboot-required, and it emits events and service checks as intended.

### CODE REVIEW

**Comment by jeremy-lq** [comment]
@antifuchs
If you're still interested in having this merged and are willing to become the maintainer, please let us know. I'm happy to explain the process a bit more if you have questions. Also note we have [Office Hours](https://github.com/DataDog/dd-agent/wiki/Community-Office-Hours) today if you'd like to chat about this real-time. Thank you for the contribution.

**Comment by antifuchs** [comment]
Aah, @jeremy-lq! Sorry for the delayed response (it was a bit of a terribly busy week over here). Yes, I'd love to take maintainership of this plugin. We use it regularly and for several things, would be great to have it in an upstream-ish repo proper!

I'll drop by the next office hours (:

**Comment by jeremy-lq** [comment]
Thanks, @antifuchs!

**Comment by gmmeyer** [comment]
@antifuchs can you fix the conflicts? You can just remove those since this test will be run with the default tests.

There's no metadata to add since it's just a service check and an event. So, I think this is pretty good. I'm good with merging this after the conflicts are fixed!

**Pull request closed without merging**
