### PR TITLE
Update nvml integration version

### PR DESCRIPTION
**Pull request by albertoperdomo2**
### What does this PR do?

Updates the version of the integration for NVML. 

### Motivation

In my last PR is was not included. 

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by jose-manuel-almaza — APPROVED** [review]

**Comment by albertoperdomo2** [comment]
@jose-manuel-almaza would you mind to explain me how the build process works after the merge? I mean, running 
```
datadog-agent integration install -t datadog-nvml==1.0.3
```
does not work, and I'm not sure what part I am missing. 

TIA!

**Comment by jose-manuel-almaza** [comment]
Hi @albertoperdomo2
Can you try agin running `datadog-agent integration install -t datadog-nvml==1.0.3` and show me the error info if it doesn't work?

**Comment by albertoperdomo2** [comment]
Yeah now it seems to be working! Thanks  🙂

**Comment by jose-manuel-almaza** [comment]
Great!

**Pull request merged**
