### PR TITLE
Fixed framework name in the doc (Angular)

### PR DESCRIPTION
**Pull request by caiofcm**
### What does this PR do?

fixed framework name

### Motivation

Fixing the correct name

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### CODE REVIEW

**Review by anediaz — COMMENTED** [review]
**question:**
shouldn't this be merged into `preprod` firstly?

**Review by anediaz — CHANGES_REQUESTED** [review]
I strongly believe this should be merged into preprod firstly

**Comment by yzhan289** [comment]
> I strongly believe this should be merged into preprod firstly

After this PR gets approved and merged, the Agent integrations team will be able to sync this change to the different regions.

**Review by anediaz — APPROVED** [review]
LGTM

**Review by sarah-witt — APPROVED** [review]

**Pull request merged**
