### PR TITLE
Making the filebeat check compatible with versions > 5.x, and making it able to use the HTTP profiler

### PR DESCRIPTION
**Pull request by wk8**
### What does this PR do?

This patch makes the filebeat check compatible with the new syntax Filebeat
started using in versions 5.x and later for its registry file.
It still maintains backward compatibility with the syntax from previous
versions.

This patch also makes it possible to push to Datadog the metrics Filebeat
exposes via its HTTP profiler, when started with the `--httpprof [HOST]:PORT`
option (see
https://www.elastic.co/guide/en/beats/filebeat/current/command-line-options.html)

It's worth noting since Filebeat reports a bunch of variables that are
counters from the last time it started, which by itself is not really interesting;
which is why we take care for these metrics to only push increments from
one check run to the next.

Added extensive tests on all of the above.

### Motivation

* The current check does not work with filebeat > 5.x
* It allows monitoring filebeat more closely, by leveraging filebeat's HTTP profiler

### Testing Guidelines

Added extensive tests.

### Versioning

- [X] Bumped the version check in `manifest.json`
- [X] Updated `CHANGELOG.md`
- [ ] If PR impacts documentation, docs team has been notified or [an issue has been opened on the documentation repository](https://github.com/DataDog/documentation/issues/new) => not sure this is needed here?

### Additional Notes

This supersedes https://github.com/DataDog/integrations-extras/pull/93 for the part about the new registry file syntax; that PR does not maintain backward-compatibility and is missing tests.

### CODE REVIEW

**Comment by wk8** [comment]
@truthbk @hush-hush @jeremy-lq @remh : would very much appreciate a review when you get a chance, thanks a lot :)

**Comment by wk8** [comment]
@rifelpet : thanks for the report, will try to get around to it soon :)

Or please feel free to make it a PR against my fork (https://github.com/wk8/integrations-extras) and then I'll be happy to merge it and update this PR with your commit. Thanks!

**Comment by rifelpet** [comment]
PR opened: https://github.com/wk8/integrations-extras/pull/1

**Comment by wk8** [comment]
Thanks @rifelpet ! Reviewing this weekend :)

**Comment by phrawzty** [comment]
Hi @wk8! Just wanted to check in with you to see if there was anything that we could help with in regards to this PR and https://github.com/wk8/integrations-extras/pull/1 . We'd love to see this PR get merged, so if there's any help or information you need from us, please don't hesitate to ask. 😄

**Comment by rifelpet** [comment]
@phrawzty done: https://github.com/DataDog/integrations-extras/pull/189

**Comment by ofek** [comment]
Superseded by https://github.com/DataDog/integrations-extras/pull/189

**Pull request closed without merging**
