### PR TITLE
Updated N2WS to version 4.1 + Added an Only-AMI support to dashboards

### PR DESCRIPTION
**Pull request by eliadeini**
### What does this PR do?
Returned N2WS folder that was deleted from master from some reasons, added dashboards support for 4.1.0 version of N2WS Backup & Recovery, added an Only AMI support to dashboards.

### Motivation
Fitting N2WS integration with DataDog to our new 4.1.0 version

### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [X] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?
I don't know why, I don't see our folder on integration-extras master branch. Added all the folder as it should be, changed only relevant files.

### CODE REVIEW

**Review by jtappa — CHANGES_REQUESTED** [review]
All of the changes to the README look like reverts of changes the documentation team has made in the past, which we don't want. Maybe this file needs to be rebased?

**Comment by eliadeini** [comment]
> 

Hi @jtappa , 
I had conflicts and both versions looked similar on GitHub's editor except for changes I wanted to add. I added another commit, adding the changes I removed.

**Review by jtappa — APPROVED** [review]
Thanks! This looks good from docs team! 👍🏻

**Review by steveny91 — CHANGES_REQUESTED** [review]
Hello 👋. Would you mind trying to resolve the merge conflicts that are being flagged? It seems it's blocking validations from running.

**Comment by eliadeini** [comment]
> Hello 👋. Would you mind trying to resolve the merge conflicts that are being flagged? It seems it's blocking validations from running.

No problem Steven. Unfortunately, I resolved these conflicts several times already, but after some time I get the same conflicts again, even though I didn't change anything. Do you have a clue why it could happen?

**Review by steveny91 — APPROVED** [review]
Looks good to me now.

**Pull request merged**
