### PR TITLE
Add instructions to get filebeat integration versions

### PR DESCRIPTION
**Pull request by OpeOnikute**
### What does this PR do?

Add instruction to get filebeat integration versions.

### Motivation

I was using the filebeat integration for the first time and found it difficult to know what the integration versions were. Had to do some digging to figure out to check the changelog.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Issue created on the docs repo [here](https://github.com/DataDog/documentation/issues/11379)

### CODE REVIEW

**Comment by OpeOnikute** [comment]
The versions in the changelog seem to be wrong too. I just tested the installation and only `1.0.0` works. When I tried `0.3.0`, I got a `NoSuchDatadogPackageVersion` error.

**Review by apigirl — DISMISSED** [review]

**Comment by OpeOnikute** [comment]
Thanks @sarah-witt will do that. 

How do I also make it clear from the changelog that the version to be used is 1.0.0? 
Can I add a line that says the current version?

e.g. Latest version - 1.0.0

**Comment by sarah-witt** [comment]
You can add a header for 1.0.0 at the top of the changelog, ie 
```
1.0.0
=====
```

**Review by sarah-witt — APPROVED** [review]
Thanks!

**Review by apigirl — APPROVED** [review]

**Comment by apigirl** [comment]
closes https://github.com/DataDog/documentation/issues/11379

**Pull request merged**
