### PR TITLE
Adding NiFi Integration

### PR DESCRIPTION
**Pull request by MovieStoreGuy**
### What does this PR do?
Adds a basic integration for NiFi

### Motivation
There was no current nifi integration

### Testing Guidelines

An overview on [testing](https://github.com/DataDog/dd-agent/blob/master/tests/README.md)
is available in our contribution guidelines.

### Versioning

- [ ] Bumped the version check in `manifest.json`
- [ ] Updated `CHANGELOG.md`
- [ ] If PR impacts documentation, docs team has been notified or [an issue has been opened on the documentation repository](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by masci** [comment]
Hope somebody can review this asap, in the meantime let me thank you for picking up all the latest code and practices we've been adding to integrations-core in the last few months, 💯

**Comment by jeremy-lq** [comment]
Thanks for the PR, @MovieStoreGuy! integrations-extras is a community-driven repository for integrations written and maintained outside Datadog. While support is on a best-effort basis, we're happy to help with code reviews and testing. The integrations won't be bundled with the agent, but will be installable on an individual basis.

With that in mind, would you be interested in being the initial maintainer for this integration? You'd be responsible for general code maintenance along with keeping an eye on PRs and issues. There's no specific time or duration commitment, but we do ask you only agree to become the maintainer if you feel it's something you'll be able to do for the foreseeable future. If you have any questions, let us know.

**Comment by MovieStoreGuy** [comment]
@jeremy-lq  I am all for this.
I have various feedback regarding the documentation that would of helped when I started if you have time to listen @jeremy-lq .

**Comment by jeremy-lq** [comment]
Thanks, @MovieStoreGuy. We'd really appreciate the feedback you have on the docs, as it's an item we're actively working on improving. I'll reach out now.

**Pull request closed without merging**
