### PR TITLE
feat(k6): ✨  add p99 metadata

### PR DESCRIPTION
**Pull request by ghostsquad**
### What does this PR do?

Add missing metadata for p99 metrics series.

### Motivation

Enables graphs to show the proper unit (milliseconds) for p99 metrics

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Not sure what tests I can write for this, please advise.

Anything else we should know when reviewing?

n/a

### CODE REVIEW

**Review by hestonhoffman — APPROVED** [review]

**Review by nathanmadams — APPROVED** [review]

**Review by jose-manuel-almaza — APPROVED** [review]

**Comment by ghostsquad** [comment]
can we get this merged please?

**Comment by jose-manuel-almaza** [comment]
@ghostsquad you have the approval, you can merge

**Comment by ghostsquad** [comment]
I didn't have a merge button on my side

**Comment by jose-manuel-almaza** [comment]
Np. Done

**Comment by ghostsquad** [comment]
Quick question, do you know how to get this change reflected in datadog?

**Pull request merged**
