### PR TITLE
Updated Trino integration default metrics.

### PR DESCRIPTION
**Pull request by kglazunov**
Added a couple of crucial metrics to the default Trino config.

### What does this PR do?

A crucial part of Trino monitoring metrics has been missed from default Trino integration, such as 
Queued time, OOM killed queries and tasks along with Input, Output data size and authorization fail, success rates.

### Motivation

I would like to see that in the default config.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

I'll create a support ticket with the link to this PR, thanks.

### CODE REVIEW

**Comment by alopezz** [comment]
@ndrluis Could you please have a look at this since you're the maintainer?

The test is failing also on master. Since this hasn't been triggered by a change in the integration itself, I'm most suspicious of the fact that the test setup is using an image with the `latest` tag. https://github.com/DataDog/integrations-extras/blob/d2159acd3a1fa7f0f3d24a04070e76f9ea95d5d3/trino/tests/docker/docker-compose.yaml#L6

So perhaps there's a newer version of Trino that has dropped or changed metrics. @ndrluis it would be great if you could give that a look.

**Review by yzhan289 — COMMENTED** [review]
Hi 👋 , we still need the original contributor @ndrluis to take a look at the PR, but it looks mostly good from our side. Can you add the new metrics that you added to the [metadata.csv](https://github.com/DataDog/integrations-extras/blob/master/trino/metadata.csv)?

**Review by ndrluis — APPROVED** [review]

**Review by ndrluis — CHANGES_REQUESTED** [review]
@kglazunov Can you tell us what trino version you are using?

**Comment by kglazunov** [comment]
> 

@ndrluis this one: https://trino.io/docs/current/release/release-380.html

**Comment by yzhan289** [comment]
@kglazunov Can you rebase from master? We have made some changes to the CI and validations, so you may need to resync. 

Also pinging @ndrluis for another review.

**Comment by alopezz** [comment]
Pinging everyone involved. This at the very least needs a rebase before being good to merge. @kglazunov @ndrluis . Otherwise we'll end up closing this due to inactivity.

**Comment by alopezz** [comment]
Closing for inactivity. Feel free to reopen if needed.

**Pull request closed without merging**
