### PR TITLE
[daemontools] adding integration.

### PR DESCRIPTION
**Pull request by truthbk**
# What's this PR do?

Adds an integration for the service manager [daemontools](http://cr.yp.to/daemontools.html).

Originally written by @gphat (https://github.com/DataDog/dd-agent/pull/2110)

# Motivation

Stripe uses daemontools to manage most of our services. Many of those services have first-class integrations within Datadog so verifying their liveness is handled elsewhere. Some of these services, however, are lightweight, internal daemons that will likely never have healthcheck endpoints or other metrics. This check would allow liveness checks and uptime tracking. The goal is to detect failed or flapping services.
# Notes
- Adds a gauge metric for `daemontools.service.uptime` (tagged with the service name) and a service check of `daemontools.is_running` tagged by service.
- `svstat` that emits the info we need usually requires root privs, so this integration needs some love from `sudoers`. This miiiight be a candidate for storage in [our repository](https://github.com/stripe/stripe-datadog-checks)?

### CODE REVIEW

**Comment by jeremy-lq** [comment]
@cory-stripe has agreed to be the maintainer for this check.

**Comment by cory-stripe** [comment]
I have indeed!

**Comment by gmmeyer** [comment]
@cory-stripe can you write a test for this? I can happily help if you'd like. After that's done, I'm happy to merge this!

**Comment by jeremy-lq** [comment]
Chatted with Cory, and re-opening at his request.

**Pull request closed without merging**
