### PR TITLE
Adding Dashboard and some README updates

### PR DESCRIPTION
**Pull request by salgattpx**
### What does this PR do?

Adding a Dashboard to the existing integration and making some minor updates to the README.

### Motivation

Adding new features to existing integration

### Review checklist

- [x ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x ] Feature or bugfix has tests
- [x ] Git history is clean
- [x ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Nothing additional

### CODE REVIEW

**Comment by ChristineTChen** [comment]
Hi @salgattpx, looks like there is a conflict in the README. The preset dashboard for PerimeterX needs to be exported via the `/screen` API, I've linked the documentation for an easy way to do that with `ddev`. Please let me know if you have any questions.

**Comment by salgattpx** [comment]
@ChristineTChen I have resolved the conflict in the README but I wasn't able to locate the ddev documentation that you mentioned so that I could export the dashboard

**Comment by hithwen** [comment]
Hallo @salgattpx, ddev is a tool that you probably have already installed, if not you can install it with `pip install datadog-checks-dev[cli]`.
It is self documented, and this is the utility you need for the export:

```
$ ddev meta dash export --help
Usage: ddev meta dash export [OPTIONS] URL [INTEGRATION]

Options:
  -a, --author TEXT  The owner of this integration's dashboard. Default is
                     'Datadog'

  -h, --help         Show this message and exit.
```

**Comment by salgattpx** [comment]
I have updated the Dashboard JSON using the JSON via ddev's dash export utility.

**Pull request merged**
