### PR TITLE
Add Kamailio/Freeswitch/Homer Integrations

### PR DESCRIPTION
**Pull request by devopsec**
### What does this PR do?

Adds integrations for kamailio SIP server, Freeswitch PBX server, and Homer HEP/GUI servers.

### Motivation

No integrations for these services existed.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Could not get my unit tests to run properly with `ddev` but tests on a live environment passed.

### CODE REVIEW

**Comment by buraizu** [comment]
Created DOCS-4445 to review.

**Comment by devopsec** [comment]
> Created DOCS-4445 to review.

Can you link to this?

**Comment by alopezz** [comment]
Thanks for your PR! Would you mind splitting this so that we get a PR per new integration?

**Comment by devopsec** [comment]
branching out into new PRs

**Pull request closed without merging**
