### PR TITLE
Backwards compatibility for Agent <=6.8

### PR DESCRIPTION
**Pull request by cswatt**
### What does this PR do?

The `integration` command only works for newer versions of the Agent. Re-added the old installation instructions with a note that they are for versions of the Agent <= 6.8. Also adds a note about the `integration` command only being available for Agent 6.8+.

### Motivation

Support request.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by l0k0ms** [comment]
In order to install an integrations extra integrations, not only one have to download the `.py` file but also the associated configuration file `.conf` and put the last one in the `conf.d/<INTEGRATION_NAME>.d/` folder.

**Comment by l0k0ms** [comment]
@cswatt I tested + documented the general process if you want to inspire/link to it: https://docs.datadoghq.com/agent/guide/community-integrations-installation-with-docker-agent/

**Comment by l0k0ms** [comment]
@cswatt I created a New PR with the proper instructions for installation and configuration and a link to the new Agent guide for other use-cases: https://github.com/DataDog/integrations-extras/pull/463

**Comment by cswatt** [comment]
Closing to defer to gus' new one

**Pull request closed without merging**
