### PR TITLE
[redis-sentinel] adding integration with SDK scaffolding/testing facilities.

### PR DESCRIPTION
**Pull request by truthbk**
## What
- Adding redis-sentinel using SDK testing/scaffolding.

### CODE REVIEW

**Comment by truthbk** [comment]
Looking good on CircleCI - tests fail because they should.

**Comment by krasnoukhov** [comment]
Is there anything I can do to get this merged and released?

**Comment by truthbk** [comment]
@krasnoukhov,

Hello. integrations-extras is a new community-driven repository for integrations written and maintained outside Datadog. While support is on a best-effort basis, we're happy to help with code reviews and testing. The integrations won't be bundled with the agent, but will be installable on an individual basis.

With that in mind, would you be interested in being the initial maintainer for the `redis-sentinel` integration? You'd be responsible for general code maintenance along with keeping an eye on PRs and issues. There's no specific time or duration commitment, but we do ask you only agree to become the maintainer if you feel it's something you'll be able to do for the foreseeable future. If you have any questions, let us know. Thanks!

**Comment by krasnoukhov** [comment]
Thanks @truthbk. Well we plan to use redis{-sentinel} integrations in foreseeable future in production, so I guess I can at least try and do my best. What do you think?

**Comment by truthbk** [comment]
Sorry for the delay @krasnoukhov (been relocating back to Europe and it's been a crazy last couple of weeks). I think that if you're happy to give it a shot, that would be awesome. Please reconfirm, and then we can work on putting the finishing touches on this one before merging! 

Thank you so much! 🙇

**Comment by krasnoukhov** [comment]
Hello @truthbk. I deployed this to production earlier today, and overall it seems to be working just fine, except of this change I had to make: https://github.com/simplepractice/integrations-extras/commit/2c57715851cb64ab24bee443c09cbb5cf1ccdeac

What would be the process to move forward?

**Comment by krasnoukhov** [comment]
Also, seems like Travis CI is failing but I'm not sure what's the reason. Will you look into it?

**Comment by masci** [comment]
@krasnoukhov indeed, it's a problem in our CI, looking at it...

**Pull request closed without merging**
