### PR TITLE
Makes contrast security public

### PR DESCRIPTION
**Pull request by hithwen**
Makes contrast security integration searchable in docs

### CODE REVIEW

**Comment by gmoore** [comment]
@hithwen I hit the approve button a little too soon. There's a few problems with our listing.

https://docs.datadoghq.com/integrations/contrastsecurity/ reads: "The Datadog-Constant integration allows you to get your Contrast logs into Datadog" 

"Constant" should be changed to "Contrast"

Also, the indentation isn't quite correct on our listing (image attached)

Screen Shot 2020-01-07 at 9 24 54 PM


I'm happy to make these changes if you let me know where to point the PR

Finally, I ran through all of the instructions tonight, and my Datadog dashboard shows an error (image attached). How can we get this resolved?

Screen Shot 2020-01-07 at 9 22 11 PM

**Comment by hithwen** [comment]
Hi @gmoore all the documentation site comes from the README.md so you can open a PR making changes to it. About the dashboard, you can clone the dashboard, edit it to fix the issues in the UI, then retrieve again the json using the API and submit the changes in the dashboard json that's on the repo.

The thing is I don't get the error, just empty: 
image
So maybe you should reach to support to help diagnose what is exactly happening.

**Comment by hithwen** [comment]
@gmoore, can you ask @kristianamitchellcontrastsecurity for my email and write me with your account name and the dashboard ID and I'll see what I can gather from your erroring dashboard

**Comment by hithwen** [comment]
@gmoore @kristianamitchellcontrastsecurity  did you have a chance to look at the updated dashboard?

**Pull request merged**
