### PR TITLE
N2WS Backup & Recovery version 4.0 (with Azure) updates

### PR DESCRIPTION
**Pull request by eliadeini**
### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?
N2WS Backup & Recovery version 4.0 is about to come out to the market, supporting also Azure cloud. 

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?
Added some Azure metrics in new dashboards

### CODE REVIEW

**Review by coignetp — APPROVED** [review]
Everything looks good on staging 👍

**Comment by coignetp** [comment]
@eliadeini I actually realised this PR was pointing to `Datadog:n2ws` and not `master`. Was that expected?

**Comment by eliadeini** [comment]
> @eliadeini I actually realised this PR was pointing to `Datadog:n2ws` and not `master`. Was that expected?

Sorry, my mistake. I'll open another merge request.
Thanks

**Comment by eliadeini** [comment]
> @eliadeini I actually realised this PR was pointing to `Datadog:n2ws` and not `master`. Was that expected?
Hi, opened https://github.com/DataDog/integrations-extras/pull/847

**Pull request merged**
