### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by humoflife**
Updated version number of integration package in the README.md to match the version 0.0.1 of the package that was created by Datadog so that users can build their agent.

Added otherwise hard to find steps for installing the agent to enhance the user experience.

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by ofek — CHANGES_REQUESTED** [review]
This is the only file that needs to be modified https://github.com/DataDog/integrations-extras/blob/master/upbound_uxp/datadog_checks/upbound_uxp/__about__.py

**Comment by humoflife** [comment]
Ofek,

Please advise which change should be made to the revised README.md. Thanks. 

Best,
Markus

**Comment by ofek** [comment]
The version update PR has been merged! Feel free to close this one.

**Comment by humoflife** [comment]
Closing this PR per Datadog / Ofek.

**Pull request closed without merging**
