### PR TITLE
Add packaging and config specs

### PR DESCRIPTION
**Pull request by ChristineTChen**
### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by hithwen** [comment]
Seems config is broken

**Comment by ChristineTChen** [comment]
@hithwen , added config specs to standardize the options. I haven't moved the metrics conf out of the conf.yaml.example as I think that refactor might be out of scope here.

**Comment by hithwen** [comment]
Pinging  @everpeace as codeowner

**Comment by everpeace** [comment]
Thanks for pinging and reforming.  I am glad you guys to maintain this!!

**Pull request merged**
