### PR TITLE
minor issues fixed

### PR DESCRIPTION
**Pull request by shahul-loginsoft**
### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Comment by shahul-loginsoft** [comment]
@nmuesch why did the test build is failed? it was worked on previous commits.

**Review by buraizu — APPROVED** [review]

**Comment by nmuesch** [comment]
Hey, apologizes for my delay in this! 

It looks like this is changing the integration code and should include a version bump. 
Can you bump the version in:
* README.md file for installation instructions
* CHANGELOG.md with a note about the fix
* __about__.py file 

The version can be something like `0.0.2`. As long as its bumped in those files, once merged a process will kick off to release a new wheel with that version number.

**Comment by shahul-loginsoft** [comment]
Hi @nmuesch 

Thanks for your suggestions. I bumped the version. please let me know if you have any questions.

**Review by ofek — APPROVED** [review]

**Comment by shahul-loginsoft** [comment]
Hi @nmuesch  

Thanks for you suggestions. I updated version in all required files but build is failed. please check it.

**Review by nmuesch — APPROVED** [review]

**Comment by nmuesch** [comment]
Hey @shahul-loginsoft, looks like it was a transient networking error. I retried the job and its all green! 
I'll go ahead and merge this in.

**Pull request merged**
