### PR TITLE
chore(zenduty): add syntax highlighting for JSON payload

### PR DESCRIPTION
**Pull request by AnilSeervi**
### What does this PR do?

- adds JSON highlighting on the payload
- use keyboard tag for keys

### Motivation

Open-source

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Will the `<kbd>` tags rendered properly on the site?

### CODE REVIEW

**Review by zenbeam — APPROVED** [review]
LGTM

**Review by urseberry — APPROVED** [review]
Screenshot 2023-01-31 at 2 08 44 PM
The &lt;kbd&gt; tag works in the docs! I took a screenshot for you. I put my name in the text also to verify that the changes actually showed up.

**Comment by AnilSeervi** [comment]
> Screenshot 2023-01-31 at 2 08 44 PM
> The &lt;kbd&gt; tag works in the docs! I took a screenshot for you. I put my name in the text also to verify that the changes actually showed up.

Thanks for the confirmation @urseberry.

**Comment by AnilSeervi** [comment]
This looks good @urseberry, can you ahead and merge this small chage?

**Review by bgoldberg122 — APPROVED** [review]

**Review by anawishnoff — APPROVED** [review]

**Pull request merged**
