### PR TITLE
Adding CoreDNS integration to Datadog.

### PR DESCRIPTION
**Pull request by shraykay**
### What does this PR do?

Adding an integration for CoreDNS -- CoreDNS emits metrics via Prometheus.
See sample events from plugins: [here](http://coredns.io/plugins/metrics), [here](https://coredns.io/plugins/cache/), and [here](https://coredns.io/plugins/proxy/).

### Motivation

Kubernetes is moving from KubeDNS -> CoreDNS starting v1.11

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

First time making a contribution! Please let me know what I may have missed, I borrowed heavily from KubeDNS's integration.

### CODE REVIEW

**Comment by jeremy-lq** [comment]
Thanks for the PR, @shraykay! integrations-extras is a community-driven repository for integrations written and maintained outside Datadog. While support is on a best-effort basis, we're happy to help with code reviews and testing. The integrations won't be bundled with the agent, but will be installable on an individual basis.

With that in mind, would you be interested in being the initial maintainer for this integration? You'd be responsible for general code maintenance along with keeping an eye on PRs and issues. There's no specific time or duration commitment, but we do ask you only agree to become the maintainer if you feel it's something you'll be able to do for the foreseeable future. If you have any questions, let us know.

**Comment by shraykay** [comment]
Sounds good! @jeremy-lq

**Comment by bobbytables** [comment]
> With that in mind, would you be interested in being the initial maintainer for this integration? You'd be responsible for general code maintenance along with keeping an eye on PRs and issues.

Can we get a discount on DataDog if we agree to this?

**Comment by shraykay** [comment]
closing this to move it to integrations-core  as per @gmmeyer 's request that this be put into core

**Pull request closed without merging**
