### PR TITLE
[proxysql] adding integration

### PR DESCRIPTION
**Pull request by truthbk**
### What does this PR do?

This PR introduces a new agent check for ProxySQL which is a high performance [MySQL proxy](http://www.proxysql.com/). ProxySQL is officially supported by Percona and is the recommended load balancer for Percona XtraDB Cluster.

Originally written by @ovaistariq (https://github.com/DataDog/dd-agent/pull/3107).

### Motivation

ProxySQL is a commonly used database proxy in MySQL and Percona XtraDB Cluster deployments, and Datadog is a popular monitoring tool. Datadog currently doesn't have any agent check for ProxySQL, hence adding this agent check to Datadog will benefit other users in the community.

### Testing Guidelines

An overview on [testing](https://github.com/DataDog/dd-agent/blob/master/tests/README.md)
is available in our contribution guidelines.

### Additional Notes

Not applicable.

### CODE REVIEW

**Comment by irabinovitch** [comment]
@ovaistariq    Let us know if you need a hand with getting tests passing, etc. Feel free to stop by our office hours as well if we can help. Next one is this morning at 10:30 PT / 13:30 EST.

**Comment by jeremy-lq** [comment]
@ovaistariq has agreed to become the maintainer for this integration. Can we get a review?

**Comment by ovaistariq** [comment]
I don't think I have permission to push my changes on `contributor/proxysql` to this repository

**Comment by jeremy-lq** [comment]
You can update the current PR with any changes you have. We'll have someone review and work with you to merge from there. Thanks, @ovaistariq.

**Comment by ovaistariq** [comment]
@jeremy-lq I cannot push to the current PR since I did not open it myself and I don't have permissions to push.

**Comment by jeremy-lq** [comment]
Closing this PR as @ovaistariq plans to open an updated version.

**Pull request closed without merging**
