### PR TITLE
Support EventStoreDB v20.6.0+

### PR DESCRIPTION
**Pull request by 01100010011001010110010101110000**
### What does this PR do?

This PR updates the EventStore integration to support EventStoreDB >=v20.6.0, and test against the latest LTS EventStoreDB release.

### Motivation

When EventStoreDB v20.6.0 was released, a number of semantics in changed in gossip, breaking this integration. Namely:

* The terminology changes to remove master/slave and replace with leader/follower
* The replacement of clone nodes with read only replicas
* The merging of the int/ext HTTP IP and port into a single interface

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

I made a major version bump because this drops support for ESDB v5 and below. ESDB v5 is out of support from EventStore themselves as of 2022.

### CODE REVIEW

**Comment by yzhan289** [comment]
Pinging maintainer @Xorima

**Review by alai97 — APPROVED** [review]

**Comment by fanny-jiang** [comment]
Bumping maintainer @Xorima

**Comment by fanny-jiang** [comment]
Bumping maintainer @Xorima

**Review by Xorima — APPROVED** [review]

**Comment by Xorima** [comment]
All approved from me @yzhan289 and @fanny-jiang sorry for the delay

**Review by yzhan289 — APPROVED** [review]

**Pull request merged**
