### PR TITLE
Revert "Update/fix k6 dashboard with the screen endpoint's output (#680)"

### PR DESCRIPTION
**Pull request by mostafa**
### What does this PR do?

This reverts PR #680.

### Motivation

The k6 dashboard does not show widget, so I want to revert it to its original dashboard, so that I can fix it in the future. This happened while @simskij was testing the dashboard.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

@ppcano and @hithwen: please review.

### CODE REVIEW

**Comment by ppcano** [comment]
@hithwen I've approved this PR. Please, let us know if we have to done something else.

**Comment by hithwen** [comment]
Hallo, just to make sure, this is the dashboard I see
image
(there is no data to show on my end cause I don't have k6) do you see something different? Do you expect to see something different?

**Comment by ppcano** [comment]
@hithwen This was the previous dashboard and the correct one at this moment.

**Comment by mostafa** [comment]
@hithwen But it didn't show up in the morning (Sweden time).

**Comment by hithwen** [comment]
So should we merge the revert or not? @ppcano @mostafa

**Comment by mostafa** [comment]
@hithwen It seems that the issue is resolved somehow. So, I'll close this PR.

**Pull request closed without merging**
