### PR TITLE
Dashboard Units adjusted

### PR DESCRIPTION
**Pull request by WoodProgrammer**
### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

### CODE REVIEW

**Review by emarsha94 — APPROVED** [review]

**Review by james-eichelbaum — APPROVED** [review]

**Comment by james-eichelbaum** [comment]
Ready to go once the merge conflict is fixed

**Comment by james-eichelbaum** [comment]
Ready to go once the merge conflict is fixed, looks like your fork is behind master

**Comment by emarsha94** [comment]
@WoodProgrammer could you rebase your branch? Once that is done, we can merge this live.

**Comment by emarsha94** [comment]
@WoodProgrammer can you please resolve the conflicts? From there, we can merge.

**Comment by WoodProgrammer** [comment]
Hello everyone,

I'm closing this PR due to some major dashboard changes and moving changes to new PR.

**Pull request closed without merging**
